
import React, { useState } from 'react';
import { 
  HelpCircle, 
  MessageCircle, 
  FileText, 
  ChevronDown, 
  ChevronUp, 
  Send, 
  Mail, 
  Phone, 
  CheckCircle2,
  LifeBuoy
} from 'lucide-react';

interface HelpDeskViewProps {
  onBack: () => void;
}

export const HelpDeskView: React.FC<HelpDeskViewProps> = ({ onBack }) => {
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(0);
  const [ticketSent, setTicketSent] = useState(false);

  const faqs = [
    {
      question: "How accurate are the estimated prices?",
      answer: "Our AI analyzes real-time market trends from major Indian e-commerce platforms like Amazon and Flipkart. However, prices can fluctuate. The estimates provided are usually within a 10-15% range of the actual current price."
    },
    {
      question: "Can I use the generated images for my portfolio?",
      answer: "Yes! All images generated by LuminaDecor are free for you to use in your personal or professional portfolio. We just ask that you don't resell the raw images as stock photos."
    },
    {
      question: "What happens if I don't like the suggested themes?",
      answer: "You can simply click 'New Project' to start over. Trying slightly different event descriptions (e.g., 'Classy Dinner' instead of 'Party') can often yield very different results."
    },
    {
      question: "Is my room photo stored on your servers?",
      answer: "No. Your privacy is paramount. Images are processed temporarily for analysis and are not permanently stored on our servers unless you explicitly save them to your local browser history."
    },
    {
      question: "Do you offer professional decorator hiring?",
      answer: "Currently, we are a design-only tool. We provide the plan and the shopping list, but the actual decoration is DIY. We are working on a 'Hire a Pro' feature for major Indian cities soon."
    }
  ];

  const handleTicketSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Simulate API call
    setTimeout(() => {
      setTicketSent(true);
    }, 1000);
  };

  return (
    <div className="animate-fade-in w-full max-w-6xl mx-auto mb-20">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h2 className="text-3xl font-heading font-bold text-slate-900 flex items-center gap-3">
            <LifeBuoy className="w-8 h-8 text-violet-600" />
            Help Desk
          </h2>
          <p className="text-slate-500 mt-1">We're here to support your creative journey</p>
        </div>
        <button 
          onClick={onBack}
          className="px-5 py-2 rounded-full border border-slate-200 text-slate-600 hover:bg-white hover:text-slate-900 transition-colors font-medium text-sm"
        >
          Close
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Column: FAQs */}
        <div className="lg:col-span-2 space-y-6">
          <div className="glass-panel p-8 rounded-2xl shadow-sm">
            <h3 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
              <FileText className="w-5 h-5 text-violet-600" />
              Frequently Asked Questions
            </h3>
            
            <div className="space-y-4">
              {faqs.map((faq, index) => (
                <div 
                  key={index} 
                  className={`border border-slate-100 rounded-xl overflow-hidden transition-all duration-300 ${openFaqIndex === index ? 'bg-violet-50/50 border-violet-100' : 'bg-white/50'}`}
                >
                  <button 
                    onClick={() => setOpenFaqIndex(openFaqIndex === index ? null : index)}
                    className="w-full flex items-center justify-between p-4 text-left font-medium text-slate-800"
                  >
                    {faq.question}
                    {openFaqIndex === index ? <ChevronUp className="w-4 h-4 text-violet-600" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
                  </button>
                  {openFaqIndex === index && (
                    <div className="px-4 pb-4 pt-0 text-slate-600 text-sm leading-relaxed animate-fade-in">
                      {faq.answer}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Quick Contact Info */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
             <div className="glass-panel p-6 rounded-2xl flex items-center gap-4">
                <div className="p-3 bg-blue-100 text-blue-600 rounded-full">
                  <Mail className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="font-bold text-slate-900">Email Support</h4>
                  <p className="text-sm text-slate-500">support@luminadecor.ai</p>
                </div>
             </div>
             <div className="glass-panel p-6 rounded-2xl flex items-center gap-4">
                <div className="p-3 bg-emerald-100 text-emerald-600 rounded-full">
                  <Phone className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="font-bold text-slate-900">Helpline (India)</h4>
                  <p className="text-sm text-slate-500">+91 1800-DECOR-AI</p>
                </div>
             </div>
          </div>
        </div>

        {/* Right Column: Contact Form */}
        <div className="lg:col-span-1">
          <div className="glass-panel p-8 rounded-2xl shadow-sm h-full relative overflow-hidden">
            <h3 className="text-xl font-bold text-slate-900 mb-2 flex items-center gap-2">
              <MessageCircle className="w-5 h-5 text-violet-600" />
              Submit a Ticket
            </h3>
            <p className="text-sm text-slate-500 mb-6">Can't find what you're looking for? Write to us.</p>

            {ticketSent ? (
              <div className="absolute inset-0 bg-white/90 backdrop-blur-sm z-10 flex flex-col items-center justify-center text-center p-8 animate-fade-in">
                <div className="w-16 h-16 bg-green-100 text-green-600 rounded-full flex items-center justify-center mb-4">
                  <CheckCircle2 className="w-8 h-8" />
                </div>
                <h4 className="text-xl font-bold text-slate-900 mb-2">Message Sent!</h4>
                <p className="text-slate-600 mb-6">Our support team will get back to you within 24 hours.</p>
                <button 
                  onClick={() => setTicketSent(false)}
                  className="text-violet-600 font-bold text-sm hover:underline"
                >
                  Send another message
                </button>
              </div>
            ) : (
              <form onSubmit={handleTicketSubmit} className="space-y-4">
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase mb-1">Subject</label>
                  <select className="w-full p-3 bg-white/50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-violet-500 outline-none">
                    <option>General Inquiry</option>
                    <option>Bug Report</option>
                    <option>Billing Issue</option>
                    <option>Feature Request</option>
                  </select>
                </div>
                
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase mb-1">Message</label>
                  <textarea 
                    required
                    rows={5}
                    placeholder="Describe your issue in detail..."
                    className="w-full p-3 bg-white/50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-violet-500 outline-none resize-none"
                  ></textarea>
                </div>

                <div className="pt-2">
                  <button 
                    type="submit"
                    className="w-full bg-slate-900 text-white py-3 rounded-xl font-bold hover:bg-slate-800 transition-all shadow-md flex items-center justify-center gap-2"
                  >
                    Send Message <Send className="w-4 h-4" />
                  </button>
                </div>
              </form>
            )}
            
            <div className="mt-8 pt-6 border-t border-slate-100 text-center">
               <p className="text-xs text-slate-400">
                 Support Hours: Mon-Fri, 9:00 AM - 7:00 PM IST
               </p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};
